name: Windows GUI

on:
  push:
    branches:
      - master
      - v2.2x
    paths:
      - '.github/workflows/build-gui_win.yml'
      - 'gui/src/**'

  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-gui_win.yml'
      - 'gui/src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          spectre: true

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: qt/
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: '6.8.0'
          target: 'desktop'
          install-deps: 'true'
          modules: 'qtserialport'
          arch: 'win64_msvc2022_64'
          dir: '${{ github.workspace }}/qt'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install NSIS
        run: |
             Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
             scoop bucket add extras
             scoop install nsis
            
      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          cd gui/src
          dir
          qmake HeadTracker.pro
          nmake

      - name: WinDeployQT
        working-directory: ${{github.workspace}}
        run: |
          mkdir output
          cp gui/src/release/HeadTracker.exe output/
          # cp gui/src/css/stylesheet.css output/
          # cp gui/src/css/Background.svg output/
          cd output
          curl -L -o bossac.exe https://github.com/dlktdr/HeadTracker/raw/master/gui/bin/bossac.exe
          windeployqt HeadTracker.exe

      - name: Make NSIS installer
        working-directory: ${{github.workspace}}
        run: |
             move output deploy\windows\nsis\
             cd deploy\windows\nsis
             makensis /X"SetCompressor /FINAL lzma" setup.nsi
             ren *.exe headtracker_win_installer.exe

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: headtracker_win_installer.exe
          path: deploy/windows/nsis/headtracker_win_installer.exe
          retention-days: 90

